# Site/Global settings
ignore_theme_config: true
repository: guesswhatisaac/guesswhatisaac.github.io
#author: Isaac Nathan Roman


# Build settings
#baseurl: "/guesswhatisaac.github.io"

sass:
  sass_dir: _sass
  

kramdown:
  syntax_highlighter: coderay

plugins:
  - jekyll-feed
