# Site/Global settings
ignore_theme_config: true


# Build settings
#baseurl: https://guesswhatisaac.github.io//
sass:
  sass_dir: _sass
  

kramdown:
  syntax_highlighter: coderay

plugins:
  - jekyll-feed
